# DRONE: bebop2
DRONE: iris
DRONE_COUNT: 5  # 4 to 5 drones
LIM_MAX: 2000  # Maximum number of iterations for each drone

SAVE_DESIRED_IMAGES: 0
SAVE_IMAGES: 0
SHOW_IMAGES: 0

cam_drone_1: 1
cam_drone_2: 1
cam_drone_3: 1
cam_drone_4: 1
cam_drone_5: 1
