# DRONE TYPE: bebop2 or iris
DRONE: bebop2
# DRONE: iris

# How many drones are used and the maximum number of iterations
DRONE_COUNT: 4 # 4 to 5 drones
LIM_MAX: 3000 # Maximum number of iterations for each drone

# Use or not use descriptor matching for obtaining the points and threshold to change the desired image from outside to inside
INIT_MODE: 1 # 0: Aruco Markers, 1: Descriptor Matching
# CHANGE_THRESHOLD_LEADER: .07 # Threshold to change the desired image from outside to inside for the leaders drones
CHANGE_THRESHOLD_LEADER: .0 # Threshold to change the desired image from outside to inside for the leaders drones
CHANGE_THRESHOLD_FOLLOWER: .015 # Threshold to change the desired image from outside to inside for the follower drones

# Save the desired images (when setting eveything up for the first time)
SAVE_DESIRED_IMAGES: 0 # True to save desired images
MODE: 0 # 0: First desired image (outside), 1: Second desired image (inside)

# Saving and showing images
SAVE_IMAGES: 0 # True to save images
SHOW_IMAGES: 0 # True to show images
