SAVE_DESIRED_IMAGES: 0
SAVE_IMAGES: 0
SHOW_IMAGES: 0

cam_drone_1: 1
cam_drone_2: 1
cam_drone_3: 1
cam_drone_4: 1

seguimiento_1: 0
seguimiento_2: 0
seguimiento_3: [1, 2]
seguimiento_4: [1, 2]

bearing_1: []
bearing_2: []
bearing_3: [.91,   .91,
            -.37,  .37,
            -.18, -.18]
bearing_4: [.91,  .91,
            -.37, .37,
            .18,  .18]

Kp: 4
Kv: 0.3