DRONE: bebop2
# DRONE: iris
DRONE_COUNT: 4  # MAX 5

SAVE_DESIRED_IMAGES: 1
SAVE_IMAGES: 0
SHOW_IMAGES: 0

cam_drone_1: 1
cam_drone_2: 1
cam_drone_3: 1
cam_drone_4: 1

seguimiento_1: [99]
seguimiento_2: [98]
seguimiento_3: [1, 2]
seguimiento_4: [1, 2]
seguimiento_5: [1, 2]

bearing_1: []
bearing_2: []
bearing_3: [.94,  .78,
           -.24,  .59,
           -.24, -.2]
bearing_4: [.78, .94,
           -.59, .24,
            .2,  .24]
bearing_5: []