SAVE_DESIRED_IMAGES: 0
SAVE_IMAGES: 0
SHOW_IMAGES: 0

cam_drone_1: 1
cam_drone_2: 1
cam_drone_3: 1
cam_drone_4: 1

seguimiento_1: [98]
seguimiento_2: [99]
seguimiento_3: [1, 2]
seguimiento_4: [1, 2]

bearing_1: []
bearing_2: []
bearing_3: [.85,  .76,
            -.45,  .6,
            -.28, -.25]
bearing_4: [.78,  .88,
            -.62, .47,
            .0,  .0]
# bearing_3: [.8,   .8,
#             -.53,  .53,
#             .27, .27]
# bearing_4: [.8,  .8,
#             -.53, .53,
#             -.27,  -.27]
# bearing_3: [.91,   .91,
#             -.37,  .37,
#             -.18, -.18]
# bearing_4: [.91,  .91,
#             -.37, .37,
#             .18,  .18]
