# The camera intrinsic parameters matrix
# 3x3 matrix
camera_intrinsic_parameters: [700, 0, 960, 0, 700, 540, 0, 0, 1]

# Sampling time
dt: 0.01

seguimiento:
  len: 2
  data: [1, 2] #1, 2, 96, 97

bearing:
  rows: 3
  cols: 2
  data: [.9, .69, -.3, .69, -.3, -.23]

# Gain on linear velocities (proportional)
gainv: 3
gainv_max: .5
gainv_prime: -4

# Gain on linear velocities (integral)
gainv_ki: 0.1
gainv_ki_max: .005
gainv_ki_prime: -0.3

# Gain on angular velocities
gainw: 0.5
gainw_max: 0.5001
gainw_prime: 1

# Threshold on the feature position error, used to stop the visual control
feature_error_threshold: .01

nfeatures: 500
scaleFactor: 1.2
nlevels: 8
edgeThreshold: 15
patchSize: 30
fastThreshold: 20
flann_ratio: 0.7

############################################################
# Cambio de control 0 (posicion)
# control 1 (diferencia de bearings)
# control 2 (proyeccion de bearing)
# control 3 (ambos)
# control 4 (proyeccion de bearing con rotaciones)
# control 5 (proyeccion de bearing con rotaciones Ground Truth)
# control 6 (diferencia de bearings con rotaciones)
# control 7 (diferencia de bearings con rotaciones Ground Truth)
control: 7

############################################################
# Cambio de c치mara 0, 1 o 2.
# 1 Para c치mara de iris - frontal
# 2 Para c치mara de iris - abajo
# 3 Para c치mara de iris - Ambas
camara: 1
