# The camera intrinsic parameters matrix
# 3x3 matrix
# Iris
camera_intrinsic_parameters: [700,   0,    960,
                              0,    700,   540,
                              0,     0,     1]

# Bebop2
# camera_intrinsic_parameters: [1505,   0,    2043,
#                               0,    1505,   1446,
#                               0,     0,     1]

# Sampling time
dt: 0.01

seguimiento: 
  len: 2
  data: [1, 2] #1, 2, 96, 97

bearing: 
  rows: 3
  cols: 2
  data: [
        .9,  .69,  
        -.3, .69,  
        -.3, -.23, 
  ]

# Gain on linear velocities
gainv: 1.5
gainv_max: 2.5

# Gain on angular velocities
gainw: .01
gainw_max: .001

# Threshold on the feature position error, used to stop the visual control
feature_error_threshold: .01

nfeatures: 500
scaleFactor: 1.2
nlevels: 8
edgeThreshold: 15
patchSize: 30
fastThreshold: 20
flann_ratio: 0.7

############################################################
# Cambio de control 0 (posicion)
# control 1 (diferencia de bearings)
# control 2 (proyeccion de bearing)
# control 3 (ambos)
control: 3

############################################################
# Cambio de c치mara 0, 1 o 2.
# 1 Para c치mara de iris - frontal
# 2 Para c치mara de iris - abajo
# 3 Para c치mara de iris - Ambas
camara: 1