# The camera intrinsic parameters matrix
# 3x3 matrix
camera_intrinsic_parameters: [241.4268236, 0,    376.0,
                              0,    241.4268236, 240.0,
                              0,    0,    1]

# Sampling time
dt: 0.01

# Gain on linear velocities
############################################################
# Para el control #1
gainv: .8
############################################################
# Para el control #2
# gain_v: .4

# Gain on angular velocities
gainw: 1

# Threshold on the feature position error, used to stop the visual control
feature_error_threshold: .06

nfeatures: 500
scaleFactor: 1.2
nlevels: 8
edgeThreshold: 15
patchSize: 30
fastThreshold: 20
flann_ratio: 0.7

############################################################
# Cambio de control 1 o 2.
control: 1

############################################################
# Cambio de c치mara 0, 1 o 2.
# 0 Para c치mara de humminbird
# 1 Para c치mara de iris - frontal
# 2 Para c치mara de iris - abajo
camara: 0