# The camera intrinsic parameters matrix
# 3x3 matrix
# Iris
camera_intrinsic_parameters: [700,   0,    960,
                              0,    700,   540,
                              0,     0,     1]

# Bebop2
# camera_intrinsic_parameters: [1505,   0,    2043,
#                               0,    1505,   1446,
#                               0,     0,     1]

R: [0, 0, -1,
    1, 0, 0,
    0, 1, 0]
    
# Sampling time
dt: 0.01

seguimiento: 
  len: 1
  data: [99] #97 or 99

bearing: 
  rows: 0
  cols: 0
  data: []

# Gain on linear velocities
############################################################
# Para el control #1
gainv: 3
gainv_max: .1
############################################################
# Para el control #2
# gain_v: .4

# Gain on angular velocities
gainw: .01
gainw_max: .001

# Threshold on the feature position error, used to stop the visual control
feature_error_threshold: .01

nfeatures: 1500
scaleFactor: 1.2
nlevels: 8
edgeThreshold: 15
patchSize: 30
fastThreshold: 20
flann_ratio: 0.7

############################################################
# Cambio de control 1 (1/dist) o 2 (dist).
control: 1

############################################################
# Cambio de c치mara 0, 1 o 2.
# 1 Para c치mara de iris - frontal
# 2 Para c치mara de iris - abajo
# 3 Para c치mara de iris - Ambas
camara: 1